version: "3.7"
services:
  app:
    image: cklitscher/phpapp:latest
    restart: always
  nginx:
    image: shiphp/nginx-env
    restart: always
    ports:
      - 8088:80
    environment:
      - NGINX_HOST=app
